[build]
  commad = "npm run build"
  publish = "dist"
  fucntions = "netlify/functions"

[dev]
  commad = "npm run dev"
  publish = "dist"
  fucntions = "netlify/functions"

[[redirects]]
  from = "/housing/:id"
  to = "/.netlify/functions/housing-info/?id=:id"
  status = 200
