[build]
  commad = "npm run build"
  publish = "dist"
  fucntions = "netlify/functions"

[dev]
  commad = "npm run dev"
  publish = "dist"
  fucntions = "netlify/functions"

[[redirects]]
  from = "/affordable-housing/:id"
  to = "/.netlify/functions/housing-info/?id=:id"
  status = 200

[[redirects]]
  from = "/units/:id"
  to = "/.netlify/functions/units/?id=:id"
  status = 200

# A more freindly URL for the affordable housing list
[[redirects]]
  from = "/Home/CollectionListNew"
  to = "/affordable-housing"
  status = 302

# Any unsatisfied requests should be proxied to the original site hosting
[[redirects]]
  from = "/*"
  to = "https://theunitedeffort.org/:splat"
  status = 200
