[build]
  commad = "npm run build"
  publish = "dist"
  fucntions = "netlify/functions"

[dev]
  commad = "npm run dev"
  publish = "dist"
  fucntions = "netlify/functions"

[[redirects]]
  from = "/housing/:id"
  to = "https://theunitedeffort.org/Home/Detail?mid=:id"
  status = 200

[[redirects]]
  from = "/Account/Login/*"
  to = "https://theunitedeffort.org/Account/Login/:splat"
  status = 200


